fix: TT-303 Create activity with active status
ioet/time-tracker-backend pull request #315
Opened 2021-08-03 17:44 UTC by jcalarcon98

## Description
When we create a new activity, the default active state is not added, which causes errors when presenting in the UI, like this: 
![image](https://user-images.githubusercontent.com/56373098/128061433-5bb1500a-c76a-47b7-9d59-8c2b1412677a.png)

## Solution
With this PR this behavior is modified and an active status is added by default

2021-08-04 19:30 UTC, ridouku requested changes

2021-08-04 19:51 UTC, jcalarcon98 commented on time_tracker_api/activities/activities_model.py
> +        activity_payload['status'] = 'active'
Resolve in internal conversation

2021-08-06 14:00 UTC, scastillo-jp approved these changes

2021-08-06 14:02 UTC, ridouku approved these changes

2021-08-06 17:29 UTC, merged