feat: TT-353 Create V2 Activities DAO
ioet/time-tracker-backend pull request #320
Opened 2021-09-24 17:43 UTC by EdansRocks

## Description
With this PR the V2 directory was created for the new version of the Time Tracker backend, according to the structure defined by the team. In addition, the DAO was created to access the activity data from a JSON format file, as well as its service. The architecture taken into account can be seen below:

![image](https://user-images.githubusercontent.com/41339889/134717454-bda66a86-4121-4556-9e75-b08bcdaaf624.png)

2021-09-27 16:49 UTC, eguezgustavo commented
@EdansRocks puedes por fa agregarle typing a los argumentos de las funciones y al valor que retornan?

2021-09-27 18:56 UTC, EdansRocks commented
> @EdansRocks puedes por fa agregarle typing a los argumentos de las funciones y al valor que retornan?

D

2021-09-28 20:34 UTC, eguezgustavo requested changes

2021-09-28 20:42 UTC, josepato87 approved these changes
LGTM

2021-09-29 15:10 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +    def get_by_id(self, id):
Done!

2021-09-29 15:11 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        activity = next(
Done!

2021-09-29 15:11 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        activity = {key: activity.get(key) for key in self.activity_keys}
Done!

2021-09-29 15:11 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +def test_get_by_id__return_activity_dto__when_find_activity_that_matches_its_id(
Done!

2021-09-29 15:11 UTC, EdansRocks commented on V2/tests/services/activity_service_test.py
> +    activities_dao_mock = mocker.patch.object(ActivitiesJsonDao, 'get_by_id')
Done!

2021-09-29 19:08 UTC, josepato87 approved these changes
Now LGTM

2021-09-30 10:10 UTC, eguezgustavo requested changes

2021-09-30 10:10 UTC, eguezgustavo commented on V2/tests/daos/activities_json_dao_test.py
> +def test_get_all__return_empty_list__when_doesnt_found_any_activities(mocker):
El nombre debería estar redactado en tercera persona

2021-09-30 10:10 UTC, eguezgustavo commented on V2/tests/services/activity_service_test.py
> +def test__get_by_id__return_activity_dto__when_find_activity_that_matches_its_id(
tercera persona

2021-09-30 10:10 UTC, eguezgustavo commented on V2/tests/services/activity_service_test.py
> +
Creo que este módulo debería tener solo dos tests, uno para get_all y otro para get_by_id. Te escribo para get_all pero te dejo a ti el de get_by_id:

```suggestion
def test__get_all__uses_the_dao_to_retrieve_activities(mocker):
    expected_activities = mocker.Mock()
    dao = mocker.Mock(get_all=mocker.Mock(return_value=expected_activities))
    service = ActivityService(dao)
    
    acutal_activities = service.get_all()
    
    assert dao.get_all.called
    assert expected_activities == actual_activities
```

2021-09-30 17:15 UTC, EdansRocks commented on V2/source/daos/activities_dao_interface.py
> +from V2.source.dtos.activity import ActivityDto
Done!

2021-09-30 17:15 UTC, EdansRocks commented on V2/source/daos/activities_dao_interface.py
> +    def get_all(self) -> list:
Done!

2021-09-30 17:33 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +    def get_by_id(self, id: str) -> ActivityDto:
Done!

2021-09-30 17:33 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +            return HTTPStatus.NOT_FOUND
Done!

2021-09-30 17:34 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +    def get_all(self) -> list:
Done!

2021-09-30 17:34 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        list_activities = []
Done!

2021-09-30 17:34 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        for activity in activities:
Done!

2021-09-30 17:34 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +    def __get_activities_from_file(self) -> list:
Done!

2021-09-30 17:38 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +    def __create_activity_dto(self, activity: dict) -> ActivityDto:
Este cambio fué un request tuyo!
![image](https://user-images.githubusercontent.com/41339889/135503732-e07e2746-b49d-4f9f-ba9d-72c7e9bd234f.png)

Para un mejor contexto, la función no sólo crea el objeto sino que limpia los atributos que utiliza el DTO de los que vienen de la data del archivo json

2021-09-30 17:39 UTC, EdansRocks commented on V2/source/dtos/activity.py
> +class ActivityDto:
Done!

2021-09-30 17:39 UTC, EdansRocks commented on V2/source/services/activity_service.py
> +from V2.source.daos.activities_dao_interface import ActivitiesDaoInterface
Done!

2021-09-30 17:39 UTC, EdansRocks commented on V2/source/services/activity_service.py
> +        activity_dto = self.activities_dao.get_by_id(id)
Done!

2021-09-30 17:39 UTC, EdansRocks commented on V2/source/services/activity_service.py
> +    def get_all(self) -> list:
Done!

2021-09-30 17:39 UTC, EdansRocks commented on V2/source/services/activity_service.py
> +        list_activities = self.activities_dao.get_all()
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +def test_get_by_id__return_activity_dto__when_find_activity_that_matches_its_id(
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +    mocker,
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +    activities_json_dao = ActivitiesJsonDao('non-important-path')
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +    activities = [
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +    ]
Done!

2021-09-30 17:40 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +def test__get_by_id__return_httpstatus_not_found__when_no_activity_matches_its_id(
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +def test_get_all__return_list_of_activity_dto__when_find_one_or_more_activities(
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +    activities_json_dao = ActivitiesJsonDao('non-important-path')
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/daos/activities_json_dao_test.py
> +def test_get_all__return_empty_list__when_doesnt_found_any_activities(mocker):
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/services/activity_service_test.py
> +
Done!

2021-09-30 17:41 UTC, EdansRocks commented on V2/tests/services/activity_service_test.py
> +def test__get_by_id__return_activity_dto__when_find_activity_that_matches_its_id(
Done!

2021-10-04 15:27 UTC, eguezgustavo approved these changes

2021-10-04 16:51 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        activity_dtos = [
Done!

2021-10-04 16:51 UTC, EdansRocks commented on V2/source/daos/activities_json_dao.py
> +        activity = activities_grouped_by_id.get(activity_id)
Done!

2021-10-04 16:59 UTC, merged