TT-384 Refactor Tables
ioet/time-tracker-backend pull request #337
Opened 2021-11-08 16:56 UTC by Jobzi

In this pull request we work on the TT-384 refactor tables ticket, in this functionality we add the connection to a container hosted in azure blob storage to read the information from a json file 'activity.json'.

We need an environment variable `AZURE_STORAGE_ACCOUNT_KEY= XXX`.

2021-11-09 19:27 UTC, RobertoCordova requested changes

2021-11-09 19:27 UTC, RobertoCordova commented on tests/commons/data_access_layer/file_stream_test.py
> +def test_get_file_stream_return_file_when_enter_file_name():
Podemos mejorar el nombre del test? veo no retorna un archivo sino un entero

2021-11-09 19:27 UTC, RobertoCordova commented on tests/commons/data_access_layer/file_stream_test.py
> +def test_get_file_stream_return_None_when_not_enter_file_name_or_incorrect_name():
Por favor sigamos el formato de los underscore dobles

2021-11-09 19:27 UTC, RobertoCordova commented on tests/time_tracker_api/activities/activities_model_test.py
> +def test_find_all_from_blob_storage(
Lo mismo que los comentarios anteriores

2021-11-09 19:27 UTC, RobertoCordova commented on time_tracker_api/activities/activities_model.py
> +        import json
Es necesario que el import este dentro de la funcion?

2021-11-09 19:27 UTC, RobertoCordova commented on time_tracker_api/activities/activities_model.py
> +    def get_all_old(
la palabra "old" es un estandart para todos los metodos de la version V1?

2021-11-09 19:48 UTC, Jobzi commented on time_tracker_api/activities/activities_model.py
> +    def get_all_old(
Este método es el antiguo que recupera la información del cosmosdb, para mantenerlo y que no sé rompa nada cambie el nombre del método a get_add_old, pues como se maneja una clase abstracta CRUDDao, estan los métodos de get, create, etc.
Pero puedo cambiar ese nombre y dejarlo como get_all_v1?

2021-11-10 16:06 UTC, RobertoCordova commented on time_tracker_api/activities/activities_model.py
> +    def get_all_old(
Por favor se puede socializar esto con el equipo y llegar a un acuerdo en el Stand up? para que todos sepan y sigan esta nomemclatura

2021-11-10 18:47 UTC, RobertoCordova approved these changes

2021-11-11 20:32 UTC, scastillo-jp approved these changes

2021-11-11 20:40 UTC, merged